In [1]:
import numpy as np
a=(1,2,3)
np.sum(a)

6

In [2]:
a=[2,3,4]
np.sum(a)

9

In [3]:
a.su(a)

AttributeError: 'list' object has no attribute 'su'

In [4]:
a.sum(a)

AttributeError: 'list' object has no attribute 'sum'

In [5]:
a=[2,3,4,5]
*a

SyntaxError: invalid syntax (<ipython-input-5-d8bc1c1b6959>, line 2)

In [6]:
print *a

SyntaxError: invalid syntax (<ipython-input-6-c96d47aaa263>, line 1)

In [7]:
a=(3,4,5)
print *a

SyntaxError: invalid syntax (<ipython-input-7-de6c151c99bf>, line 2)

In [8]:
a=(3,4,5)
print *a

SyntaxError: invalid syntax (<ipython-input-8-de6c151c99bf>, line 2)

In [9]:
a=(3,4,5)
*a

SyntaxError: invalid syntax (<ipython-input-9-3f70c8018a58>, line 2)

In [10]:
a=[3,4,5]
def sum(a,b,c):
     print a+b+c
sum(*a)        

12


In [13]:
a=np.linspace(0,3,num=10)

In [16]:
a.append(1)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [17]:
np.linspace(1,10,num=20)

array([  1.        ,   1.47368421,   1.94736842,   2.42105263,
         2.89473684,   3.36842105,   3.84210526,   4.31578947,
         4.78947368,   5.26315789,   5.73684211,   6.21052632,
         6.68421053,   7.15789474,   7.63157895,   8.10526316,
         8.57894737,   9.05263158,   9.52631579,  10.        ])

In [18]:
np.linspace(4,5,num=10)

array([ 4.        ,  4.11111111,  4.22222222,  4.33333333,  4.44444444,
        4.55555556,  4.66666667,  4.77777778,  4.88888889,  5.        ])

In [19]:
np.linspace(4,5,num=10)

array([ 4.        ,  4.11111111,  4.22222222,  4.33333333,  4.44444444,
        4.55555556,  4.66666667,  4.77777778,  4.88888889,  5.        ])